# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push images
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image for api
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'brihulse/rp-todo-demo'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build and Push image for test runner container
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'brihulse/rp-todo-demo-postman-runner'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/postman/Dockerfile'
        tags: |
          $(tag)
          latest
- stage: Deploy
  displayName: Deploy to Azure Container Instance
  jobs:
  - job: Deploy
    displayName: Deploy container as ACI
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(1a11cb2d-d5b0-4863-b078-3e4840403fea)'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(Build.SourcesDirectory)/ps1/create_api_aci.ps1'
        failOnStandardError: true
- stage: Test
  displayName: Run tests in Azure Container Instance
  jobs:
  - job: Test
    displayName: Test in ACI
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(1a11cb2d-d5b0-4863-b078-3e4840403fea)'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(Build.SourcesDirectory)/ps1/run_aci_tests.ps1'
        failOnStandardError: true