# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push images
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image for api
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'brihulse/rp-todo-demo'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build and Push image for test runner container
      enabled: false
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'brihulse/rp-todo-demo-postman-runner'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/postman/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: CopyFiles@2
      displayName: Publish powershell to build artifacts
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/ps1'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/publish/ps1'
    - task: CopyFiles@2
      displayName: Publish postman src to build artifacts
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/postman/src'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/publish/postman'
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/publish'
        ArtifactName: 'drop'
        publishLocation: 'Container'