# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push image
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'brihulse/rp-todo-demo'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
- stage: Deploy
  displayName: Deploy to Azure Container Instance
  jobs:
  - job: Deploy
    displayName: Deploy container as ACI
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create --resource-group todo-api-demo-rg --name demo-container --image docker.io/brihulse/rp-todo-demo --dns-name-label rp-todo-demo --ports 80 --location centralus'